### ISSUE TITLE
allow overriding the server used in `namespacelabs.dev/foundation/library/oss/postgres` + `namespacelabs.dev/foundation/library/database/postgres:Cluster`

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#1000]
This is similar to how nix allows overriding individual packages.

**Comment by hugosantos** [comment]
fyi @n-g

**Comment by hugosantos** [comment]
We'll have to change https://github.com/namespacelabs/foundation/blob/8701dd324b3de9838a597685df0f13902db96dbb/library/oss/postgres/providers.cue#L11-L27 to support receiving a server package ref as part of the intent.

**Comment by n-g** [comment]
To discuss the alternative explicitly:

Adding the server package to the intent would require the provider to run a prepare tool instead of an initializer, so that it can manipulate the stack. 

Alternative would be to turn the server resource dependency into an input resource. That would make the stack handling more automatic, but might feel odd when instantiating the resource.

So yeah, for users of the resource, it's probably easier to just fill a field in the intent.

**Comment by hugosantos** [comment]
This is now done.
