### ISSUE TITLE
Enable shareable configurations via workspace

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#983]
At the moment, configuration is attached to the environments exclusively via devhost.textpb.

There are common configurations though that are meant to be shared, for example, which cluster to use with a particular environment. Rather than document which `prepare` statements someone should run, shared environments should be committed into the repository.

As environment definitions live under `ns-workspace.cue`, it would be natural to extend it with configurations that would otherwise live in `devhost.textpb`.

```cue
environment: {
  prod: {
    configuration: [
      {type_url: "type.googleapis.com/foundation.providers.aws.Conf" value: {profile: "prod-main"}}
    ]
  }
}
```

Unlike `devhost.textpb` which uses text protobuf for serialization, we'd use our proto any handling in parsing above.

**Comment by AvineshTripathi** [comment]
Hey @hugosantos I am interested in this issue can you give me some more details on what exactly `extending the ns-workspace.cue config with shared config` means(is it like just copying that into ns-workspace struct or creating a new field that keeps the shared configs ).

Also do you have any rough path in your mind that would help me start in correct direction

**Comment by n-g** [comment]
Hey @AvineshTripathi 
Great to hear your interested in taking this issue! Solving this would greatly improve the experience of using Namespace as a team.

Let me walk you through how we think about this:

### Background

Namespace uses two files to manage development environments: `ns-workspace.cue` and `devhost.textpb`

`ns-workspace.cue` is committed to the repository and shared with your team.
This is where we define which environments exist for the workspace.
For example: 

```
environment: {
	dev: {
		runtime: "kubernetes"
		purpose: "DEVELOPMENT"
	}
	prod: {
		runtime: "kubernetes"
		purpose: "PRODUCTION"
	}
}
```

`devhost.textpb` on the other hand is not committed to the repository. So it is private to you and contains configuration for each environment (which may be specific to your local machine).

For example, you might use a self-configured, local Kubernetes cluster for development:

```
configure: {
  name:  "dev"
  configuration:  {
    [type.googleapis.com/foundation.runtime.kubernetes.HostEnv]: {
      kubeconfig: "~/.kube/config"
      context: "my-local-kubernetes-context"
    }
  }
}
```

See also https://namespace.so/docs/concepts/packages#workspace

Now, let's say my team uses AWS EKS for production deployments.
Today, you'd set this up by running `ns prepare eks --env=prod --cluster=prodekscluster --aws_profile=my-prod-profile` which adds
```
configure: {
  name:  "prod"
  configuration: {
    [type.googleapis.com/foundation.universe.aws.configuration.Configuration]: {
      profile:  "my-prod-profile"
    }
  }
  configuration:  {
    [type.googleapis.com/foundation.universe.aws.configuration.eks.Cluster]:  {
      name:  "prodekscluster"
    }
  }
}
```
to your `devhost.textpb`

From these configuration bits, the AWS profile is again machine-specific and depends on your local AWS config.
The EKS cluster name, however, should be consistent for all team members.

It would be great if we could split the configuration, so that 
```
configure: {
  name:  "prod"
  configuration: {
    [type.googleapis.com/foundation.universe.aws.configuration.Configuration]: {
      profile:  "my-prod-profile"
    }
  }
}
```
would remain in `devhost.textpb` and we would add 
```
environment: {
  prod: {
    configuration: [{
      type_url: "type.googleapis.com/foundation.universe.aws.configuration.eks.Cluster"
      value: {name:  "prodekscluster"}
    }]
  }
}
```
to `ns-workspace.cue` instead.

### How to get there

First, it would be great to enable configuration bits to live in both places, `devhost.textpb` and `ns-workspace.cue`.

That requires extending environment parsing at https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/internal/frontend/cuefrontend/module.go#L226-L227 to permit specifying configuration from a workspace file and then merging with any configuration coming from devhost.
We should also check that the configurations don't conflict.

Once we have that, we can already edit workspace files by hand to specify team-level configuration.

After that it would be great make the user experience more delightful.
For example, if you already have an EKS cluster defined in your workspace, `ns prepare eks` should only ask you for the AWS profile to use.

Let me know if this makes sense :)

**Comment by AvineshTripathi** [comment]
Thank you @n-g that described me clearly about the working of the project along with the issue statement. Can you give me a bit more explanation on 
`to permit specifying configuration from a workspace file and then merging with any configuration coming from devhost.` 
 question: 
- currently we dont support specifying configuration from `ns-workspace.cue` file (I could not find the implementation of https://github.com/namespacelabs/foundation/blob/main/schema/workspace.pb.go#L500) so we are to add another field same like purpose, runtime under environments. 
- secondly when the user hit the `prepare` command for the first time we will call a function that would append configuration to the above mentioned struct i
 
are the above two approaches correct?

Another question is what if a team member updates the name in its `devhost` file so wont other team member with different devHost file create a conflict

**Comment by n-g** [comment]
Namespace uses [protocol buffers](https://developers.google.com/protocol-buffers) for data modeling.
We parse various inputs into this data model (textproto in case of devhost, [CUE](https://cuelang.org/) for the workspace definition).

For the workspace, you can see that the proto data model already allows to specify a configuration
https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/schema/workspace.pb.go#L36-L37
https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/schema/workspace.pb.go#L500-L501

But we don't fill it yet when parsing CUE.
So the first step would be to add `configuration` to the CUE model https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/internal/frontend/cuefrontend/module.go#L549-L550
and use it to fill `configuration` in the proto model
https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/internal/frontend/cuefrontend/module.go#L226-L227

When parsing devhost, we validate that the used type is valid
https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/internal/parsing/devhost/load.go#L53-L54
We should replicate that for the new parsing path in workspace.

Namespace will already consider configurations from both fields in the data model
https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/std/cfg/context.go#L35-L38
However, currently it just appends configuration from both, without checking for collisions:
https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/std/cfg/configuration.go#L66-L67

Instead, we should check if there is any configuration type with two conflicting specs.
(For example with https://github.com/namespacelabs/foundation/blob/941bd917636a9f5495acd7bba62db4ba8f5880a7/internal/protos/consolidate.go#L13-L14 )

I would not touch `ns prepare` for now, to keep the first change simple to reason about.

Let me know if that clears it up :)

**Comment by AvineshTripathi** [comment]
Yep that clears a lot please assign this to me I am starting working on this

**Comment by AvineshTripathi** [comment]
Hey @n-g I am working on the issue however I have a blocker so for the new configuration added to `ns-workshop.cue` 
```
        dev: {
		runtime: "kubernetes"
		purpose: "DEVELOPMENT"
		configuration: [{
      		    type_url: "type.googleapis.com/foundation.universe.aws.configuration.eks.Cluster"
      		    value: {name:  "prodekscluster"}
    	        }]
	}
```

I am not able to parse `value: {name:  "prodekscluster"}` as the error says `    failed to decode workspace contents: environment.dev.configuration.0.value: cannot use value {name:"prodekscluster"} (type struct) as list `

can you guide me if I have to manually parse the value field to `[]byte` and if so what is the correct place to do that in the code

**Comment by nicolasalt** [comment]
Hi Avinesh,

First, if you want "configuration" to have a flexible structure, without a pre-defined schema (so the "value" can be any json), one of the ways to do that is to implement `jsonUnmarshaler` and do custom parsing from json there. Example: https://github.com/namespacelabs/foundation/blob/cf53bf97e47480edbc7639a2316bdef16a31c7e6/internal/frontend/cuefrontend/args/args.go#L19

Then, you'll need to convert from json and the type URL to `anypb.Any`. Here is an example of how it is done in other place: https://github.com/namespacelabs/foundation/blob/cf53bf97e47480edbc7639a2316bdef16a31c7e6/internal/frontend/cuefrontend/server.go#L204

Let me know if you have more questions.

**Comment by AvineshTripathi** [comment]
Hey folks I have given many attempts in order to solve the issue however I feel the flow of the project is a bit complex to me, I definately got idea about parts of project but couldnot connect them together so I am stepping down from the issue to not delay more. 

However if anyone is taking up the issue would definately like to see the approach while solving the issue. Would definately like to take up new task related to the project, something that can give me more view of the project

**Comment by n-g** [comment]
Thank you for spending your time on this - really appreciate it! Our core codebase is already quite complex and evolves quickly, so it can be very hard to jump in and contribute at this point. Over time, we'll improve our architecture documentation which will make it easier to tackle issues like this one.

**Comment by AvineshTripathi** [comment]
@n-g please let me know if I can collaborate with the team in the efforts of improving while doing so maybe I'll get a better understanding and a good walk through of the codebase
